### PR TITLE
Fixed sorting quizzes by descending date order

### LINKED ISSUE #7: Quizzes are sorted with all afternoon quizzes before the morning ones
Ideally we sort by date, which alternates morning and afternoon

### PR DESCRIPTION
**Pull request by AlDrag**
Fixes #7

### CODE REVIEW

File: script.js [hunk 1]
```diff
@@ -46,3 +46,7 @@ function getIframeSrc(htmlContent) {
   const match = regex.exec(htmlContent);
   return match ? match[1] : '';
 }
+
+function parseStuffQuizDateString(dateString) {
```
Comment (ZeroX-DG) [inline script.js:50]: This is no longer required! It's time to get rid of it.

**Review by ZeroX-DG — CHANGES_REQUESTED** [review]

**Review by ZeroX-DG — APPROVED** [review]
LGTM 🎉
